//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class MoveFeedback : Message
    {
        public const string k_RosMessageName = "franka_msgs/Move";
        public override string RosMessageName => k_RosMessageName;

        public double current_width;
        //  [m]

        public MoveFeedback()
        {
            this.current_width = 0.0;
        }

        public MoveFeedback(double current_width)
        {
            this.current_width = current_width;
        }

        public static MoveFeedback Deserialize(MessageDeserializer deserializer) => new MoveFeedback(deserializer);

        private MoveFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_width);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_width);
        }

        public override string ToString()
        {
            return "MoveFeedback: " +
            "\ncurrent_width: " + current_width.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
