//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetCartesianStiffnessRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetCartesianStiffness";
        public override string RosMessageName => k_RosMessageName;

        //  Cartesian stiffness represented as (x, y, z, roll, pitch, yaw).
        //  The values are used in the direction of the stiffness frame.
        public double[] cartesian_stiffness;

        public SetCartesianStiffnessRequest()
        {
            this.cartesian_stiffness = new double[6];
        }

        public SetCartesianStiffnessRequest(double[] cartesian_stiffness)
        {
            this.cartesian_stiffness = cartesian_stiffness;
        }

        public static SetCartesianStiffnessRequest Deserialize(MessageDeserializer deserializer) => new SetCartesianStiffnessRequest(deserializer);

        private SetCartesianStiffnessRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cartesian_stiffness, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cartesian_stiffness);
        }

        public override string ToString()
        {
            return "SetCartesianStiffnessRequest: " +
            "\ncartesian_stiffness: " + System.String.Join(", ", cartesian_stiffness.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
