//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetJointStiffnessRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetJointStiffness";
        public override string RosMessageName => k_RosMessageName;

        //  Impedance for each joint in the internal controller
        public double[] joint_stiffness;

        public SetJointStiffnessRequest()
        {
            this.joint_stiffness = new double[7];
        }

        public SetJointStiffnessRequest(double[] joint_stiffness)
        {
            this.joint_stiffness = joint_stiffness;
        }

        public static SetJointStiffnessRequest Deserialize(MessageDeserializer deserializer) => new SetJointStiffnessRequest(deserializer);

        private SetJointStiffnessRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_stiffness, sizeof(double), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_stiffness);
        }

        public override string ToString()
        {
            return "SetJointStiffnessRequest: " +
            "\njoint_stiffness: " + System.String.Join(", ", joint_stiffness.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
