//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetLoadRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetLoad";
        public override string RosMessageName => k_RosMessageName;

        //  The mass of the object
        public double mass;
        //  Position of the center of mass
        public double[] center_of_mass;
        //  Inertia of the object - the provided 3x3 matrix is in column major form.
        public double[] load_inertia;

        public SetLoadRequest()
        {
            this.mass = 0.0;
            this.center_of_mass = new double[3];
            this.load_inertia = new double[9];
        }

        public SetLoadRequest(double mass, double[] center_of_mass, double[] load_inertia)
        {
            this.mass = mass;
            this.center_of_mass = center_of_mass;
            this.load_inertia = load_inertia;
        }

        public static SetLoadRequest Deserialize(MessageDeserializer deserializer) => new SetLoadRequest(deserializer);

        private SetLoadRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mass);
            deserializer.Read(out this.center_of_mass, sizeof(double), 3);
            deserializer.Read(out this.load_inertia, sizeof(double), 9);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mass);
            serializer.Write(this.center_of_mass);
            serializer.Write(this.load_inertia);
        }

        public override string ToString()
        {
            return "SetLoadRequest: " +
            "\nmass: " + mass.ToString() +
            "\ncenter_of_mass: " + System.String.Join(", ", center_of_mass.ToList()) +
            "\nload_inertia: " + System.String.Join(", ", load_inertia.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
