//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class SetStiffnessFrameRequest : Message
    {
        public const string k_RosMessageName = "franka_msgs/SetStiffnessFrame";
        public override string RosMessageName => k_RosMessageName;

        //  Sets the transformation matrix describing the stiffness frame relative to the TCP frame.
        //  A 4x4 column-major transformation matrix representing the position and orientation.
        public double[] transformation;

        public SetStiffnessFrameRequest()
        {
            this.transformation = new double[16];
        }

        public SetStiffnessFrameRequest(double[] transformation)
        {
            this.transformation = transformation;
        }

        public static SetStiffnessFrameRequest Deserialize(MessageDeserializer deserializer) => new SetStiffnessFrameRequest(deserializer);

        private SetStiffnessFrameRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.transformation, sizeof(double), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.transformation);
        }

        public override string ToString()
        {
            return "SetStiffnessFrameRequest: " +
            "\ntransformation: " + System.String.Join(", ", transformation.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
